/* This file is auto-generated by scripts/generateProgramImageManifest.mjs. Do not edit manually. */
export const PROGRAM_IMAGE_MANIFEST: Record<string, string[]> = {
  "nama-ruchi": [
    "/program-images/nama-ruchi/nama-ruchi.jpg"
  ],
  "nikunja-utsavam": [
    "/program-images/nikunja-utsavam/nikunja-utsavam.jpg",
    "/program-images/nikunja-utsavam/NK-1.jpg",
    "/program-images/nikunja-utsavam/NK-2.jpg",
    "/program-images/nikunja-utsavam/Nk-3.jpg"
  ],
  "radha-kalyanam": [
    "/program-images/radha-kalyanam/RK-1.jpg",
    "/program-images/radha-kalyanam/RK-2.jpg",
    "/program-images/radha-kalyanam/RK-3.jpg",
    "/program-images/radha-kalyanam/RK-4.jpg",
    "/program-images/radha-kalyanam/RK-5.jpg",
    "/program-images/radha-kalyanam/RK-6.jpg",
    "/program-images/radha-kalyanam/RK-7.jpg"
  ]
};
