import fs from 'node:fs';
import path from 'node:path';

const projectRoot = process.cwd();
const publicImagesRoot = path.join(projectRoot, 'public', 'program-images');
const outputFilePath = path.join(projectRoot, 'generated', 'programImageManifest.ts');

const SUPPORTED_IMAGE_EXTENSIONS = new Set([
  '.jpg',
  '.jpeg',
  '.png',
  '.webp',
  '.avif',
  '.gif',
]);

const getProgramImageManifest = () => {
  const manifest = {};

  if (!fs.existsSync(publicImagesRoot)) {
    return manifest;
  }

  const folderEntries = fs
    .readdirSync(publicImagesRoot, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name, undefined, { numeric: true }));

  for (const folderEntry of folderEntries) {
    if (!folderEntry.isDirectory()) {
      continue;
    }

    const folderName = folderEntry.name;
    const folderPath = path.join(publicImagesRoot, folderName);
    const imageUrls = fs
      .readdirSync(folderPath, { withFileTypes: true })
      .sort((left, right) => left.name.localeCompare(right.name, undefined, { numeric: true }))
      .filter((entry) => entry.isFile())
      .filter((entry) => SUPPORTED_IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase()))
      .map((entry) => {
        const encodedFolder = encodeURIComponent(folderName);
        const encodedFile = encodeURIComponent(entry.name);
        return `/program-images/${encodedFolder}/${encodedFile}`;
      });

    if (imageUrls.length > 0) {
      manifest[folderName] = imageUrls;
    }
  }

  return manifest;
};

const manifest = getProgramImageManifest();
const outputFileContents = `/* This file is auto-generated by scripts/generateProgramImageManifest.mjs. Do not edit manually. */
export const PROGRAM_IMAGE_MANIFEST: Record<string, string[]> = ${JSON.stringify(manifest, null, 2)};\n`;

fs.mkdirSync(path.dirname(outputFilePath), { recursive: true });
fs.writeFileSync(outputFilePath, outputFileContents, 'utf8');

console.log(`Generated ${path.relative(projectRoot, outputFilePath)} with ${Object.keys(manifest).length} program image folders.`);
